### //Buat Super
POST http://localhost:5011/admin
Content-Type: application/json

{
"Nama" : "Monika", 
"Username" : "bibi", 
"Password" : "123456", 
"confPassword" : "123456"
}

### //Login

POST http://localhost:5011/login
Content-Type: application/json

{
"Username" : "bibi", 
"Password" : "123456" 
}

###

POST http://localhost:5011/kuisioner
Content-Type: application/json

{
    "LinkKui" : "uriadutu"
}
###
GET http://localhost:5011/me

###
DELETE http://localhost:5011/logout

###
GET http://localhost:5011/admin
